import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
// import Header from "@/components/layout/header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SanityLive } from "@/sanity/live";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Chef Morgan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} font-sans min-h-screen grid grid-rows-[auto_1fr_auto] grid-cols-1`}
      >
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
